@startuml structure
title Uno player bot diagram
left to right direction

enum Value {
    A
    1 2 3 4 5 6 7 8 9 10
    V
    D
    R
    C
}

enum Suit {
    DIAMONDS
    CLUBS
    HEARTS
    SPADES
}

struct Card {
    Value value
    Suit suit
}

enum Action {
    SAY
    DISCARD
    BUY
    TURN
}

interface CardService {
    Value readValue(char* card)
    Suit readSuit(char* suit)
    Card readCard(char* cardIn)
    --
    char* getValue(Card card)
    char* getSuit(Card card)
    char* getCard(Card card)
    --
    bool isBlackCard(Card card)
    bool canPutTable(Card card, Card table)
    bool canChangeColor(Card card)
}

interface GameService {
    Hand readHand(char* complement)
    Action readAction(char* action)
    --
    void say(char* message)
    void buy(int n)
    void discard(Card card, Card* tableCard, Analyzer you)
    --
    bool checkMyTurn(char* id, char* myID)
    int checkTableToBuy(Card table)
    --
    void dropCardAndUpdate(int index, Hand hand, int* handSize)
    void addCardAndUpdate(Card newCard, Hand hand, int* handSize)
}

struct Analyzer {
    int values[VALUES_NUM];
    int suits[SUITS_NUM];
}

interface PredictorService {
    void initAnalyzer(Analyzer* analyzer, Hand hand, int handSize)
    void analyzeNew(Analyzer* analyzer, Card card)
    void revertAnalyzer(Analyzer* analyzer, Card card)
    --
    Suit chooseMaxSuit(Analyzer you)
    --
    int findCardByValue(Value value, Card table, Hand hand, int handSize)
    int chooseSpecialCard(Card table, Hand hand, int handSize)
    int getMaxSuitFrequency(Analyzer you, int handSize)
    --
    int randomPercentage(int auxSeed)
    int valueStatus(Analyzer you, Analyzer oppoent, Value value)
    int suitStatus(Analyzer you, Analyzer oppoent, Suit suit)
    int chooseCard(Analyzer you, Analyzer opponent, Card table, Hand hand, int handSize)
}

Value ..> Card
Suit ..> Card

Card .> CardService

Card .> GameService
CardService -> GameService
Action .> GameService

Analyzer .> PredictorService
Card .> PredictorService

PredictorService --> GameService

@enduml